### ISSUE TITLE
Versions and Releases

### ISSUE THREAD

**Issue by ofoxborn** [dequelabs/axe-core-maven-html#109]
Hello!
We are currently using **axe-selenium version 3.0.** 
We saw that you have other versions available, including 3.1-Snapshot and 4.0  in github. Are these a replacement or we can continue using 3.0? Do you suggest we continue using 3.0 or start using newer versions? If we must switch, which maven repository actively has these dependencies? 

Also, does the axe-min.js file and other js files we use in the project have to be downloaded from a matching version? Such as, The axe-min.js file taken from v. 3.0. Is it going to be compatible with newer versions or we have to get a new one?

Thank you!

**Comment by AdnoC** [comment]
You can continue to use 3.0 if you want. You should be able to upgrade to 3.1 without any difficulties. The 4.x line has breaking changes, so you would need to change your test code.

You should be able to use any newer version of axe-core in your code. 

We publish to [`com.deque.html.axe-core:selenium`](https://search.maven.org/artifact/com.deque.html.axe-core/selenium).

Benefits of upgrading to 4.x:
* axe results as java objects
* axe-core actually bundled rather than coincidentally in the test folder of the git repo
* The bundled axe-core major and minor version numbers will match the version of axe-core-maven-html you use
* Improved api

**Comment by bourne23** [comment]
Thank you for your response.
We tried upgrading to version 3.1, but couldn't find it anywhere. Can you please point us to the correct repository?
